// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBe4yMbPYKVzYuCJxlM4tUDn-Yvk_hhyJ0',
    appId: '1:770956510519:web:b01c8c39b3ebc2617506b2',
    messagingSenderId: '770956510519',
    projectId: 'flutter-firebase-codelab-92873',
    authDomain: 'flutter-firebase-codelab-92873.firebaseapp.com',
    storageBucket: 'flutter-firebase-codelab-92873.firebasestorage.app',
    measurementId: 'G-8D68Q2HY6Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxOoGLg1IslR85x8iwOIde7_LewcVUP-0',
    appId: '1:770956510519:android:c0a464b4964991de7506b2',
    messagingSenderId: '770956510519',
    projectId: 'flutter-firebase-codelab-92873',
    storageBucket: 'flutter-firebase-codelab-92873.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAb7gEddq8-SdER7D6SoW0CM4b6E-TdDMA',
    appId: '1:770956510519:ios:96d9b8e1c11ad21b7506b2',
    messagingSenderId: '770956510519',
    projectId: 'flutter-firebase-codelab-92873',
    storageBucket: 'flutter-firebase-codelab-92873.firebasestorage.app',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAb7gEddq8-SdER7D6SoW0CM4b6E-TdDMA',
    appId: '1:770956510519:ios:96d9b8e1c11ad21b7506b2',
    messagingSenderId: '770956510519',
    projectId: 'flutter-firebase-codelab-92873',
    storageBucket: 'flutter-firebase-codelab-92873.firebasestorage.app',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
